In [36]:
import numpy as np

A = np.array([[56, 0, 4.4, 68.0],
             [1.2, 104, 52, 8],
             [1.8, 135, 99, 0.9]])

print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [37]:
# Vertical sum, i.e. axis=0
cal = A.sum(axis=0)
print(cal)
#np.reshape(cal,(2,2))

[ 59.  239.  155.4  76.9]


In [38]:
percentValue = A/cal*100
print(percentValue.round(2))

[[94.92  0.    2.83 88.43]
 [ 2.03 43.51 33.46 10.4 ]
 [ 3.05 56.49 63.71  1.17]]


In [41]:
# Reshape(1,4) here is just to be sure about the shape of row
percentValue = A/cal.reshape(1,4)*100
print(percentValue.round(2))

[[94.92  0.    2.83 88.43]
 [ 2.03 43.51 33.46 10.4 ]
 [ 3.05 56.49 63.71  1.17]]
