In [2]:
import numpy as np

# This array is funny because we don't know if it is a row or a column
a = np.random.randn(5)

In [3]:
print(a)

[-1.08551172  0.40275348  1.0872583   1.52085771 -1.48642024]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[-1.08551172  0.40275348  1.0872583   1.52085771 -1.48642024]


In [7]:
np.dot(a,a.T)

7.0451300043678735

In [8]:
np.dot(a.T,a)

7.0451300043678735

In [11]:
b = np.random.randn(5)
c = b.T
print(b)
print(c)

[-0.49100731  0.80478511  1.9722609  -1.09501573 -2.72275437]
[-0.49100731  0.80478511  1.9722609  -1.09501573 -2.72275437]


In [13]:
dotbc = np.dot(b,c)
print(dotbc)

13.391031125611551


In [15]:
dotcb = np.dot(c,b)
print(dotcb)

13.391031125611551
