In [2]:
import numpy as np

# This array is funny because we don't know if it is a row or a column
a = np.random.randn(5)

In [3]:
print(a)

[-1.08551172  0.40275348  1.0872583   1.52085771 -1.48642024]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[-1.08551172  0.40275348  1.0872583   1.52085771 -1.48642024]


In [7]:
np.dot(a,a.T)

7.0451300043678735

In [8]:
np.dot(a.T,a)

7.0451300043678735

In [25]:
dotde = np.dot(d,e)
print(dotde)

[[-3.59162898e-03 -3.16413495e-02  3.44925933e-02 -5.89759313e-02
   6.84899898e-02]
 [ 5.62786805e-02  4.95801044e-01 -5.40478332e-01  9.24117612e-01
  -1.07319722e+00]
 [-2.36881142e-02 -2.08686338e-01  2.27491340e-01 -3.88967959e-01
   4.51716674e-01]
 [-1.10873442e-01 -9.76767188e-01  1.06478497e+00 -1.82058463e+00
   2.11428323e+00]
 [ 1.13087812e-03  9.96275233e-03 -1.08605091e-02  1.85694544e-02
  -2.15650981e-02]]


In [26]:
doted = np.dot(e,d)
print(doted)

[[-1.12244897]]


In [30]:
# Element-wise multiplication
r = np.array([[2,1],[1,3]])
r*r

array([[4, 1],
       [1, 9]])

In [32]:
# Matrix multiplicatioin
r = np.array([[2,1],[1,3]])
np.dot(r,r)

array([[ 5,  5],
       [ 5, 10]])

In [41]:
x = np.random.randn(8,1)
x.reshape(2,1,4)
#x.reshape(-1,3)

array([[[-1.15969081,  2.19386055, -1.11469728, -1.3889408 ]],

       [[ 0.71419594, -0.08090823, -1.05835103, -0.67727289]]])

In [49]:
a1 = np.random.randn(3,3)
print(a1)

a2 = np.array([2,2,1])
print(a2)

a2n = a2.reshape(3,1)
print(a2n)

c1 = a1*a2
print(c1)

[[-0.62627037 -1.04733564 -1.54567903]
 [-0.16191755 -1.65047294  0.08443062]
 [-1.18398804 -1.38032963  0.11216425]]
[2 2 1]
[[2]
 [2]
 [1]]
[[-1.25254073 -2.09467128 -1.54567903]
 [-0.32383509 -3.30094589  0.08443062]
 [-2.36797609 -2.76065927  0.11216425]]


In [52]:
a = np.random.randn(4,3)
b = np.random.randn(1,3)

c = a*b
c.shape

(4, 3)

In [70]:
a = np.array([[1,1],[1,-1]])
b = np.array([[2],[3]])

print(a)
print(b)
print(a+b)

[[ 1  1]
 [ 1 -1]]
[[2]
 [3]]
[[3 3]
 [4 2]]


In [74]:
a = np.random.randn(4,1)
b = np.random.randn(4,1)

abdot = a*b

In [94]:
a = np.array([1,2,3,4])
ra = a.reshape(1,4)
print(ra)
print(a.shape)
b = np.array([[4],[1],[2],[3]])
print(b.shape)
a2 = a*a

print(a*a)
print(b)
print(a.reshape(-1,1))

v = a.reshape(a.shape[0],1)

print(a.shape[0])
print(v)

[[1 2 3 4]]
(4,)
(4, 1)
[ 1  4  9 16]
[[4]
 [1]
 [2]
 [3]]
[[1]
 [2]
 [3]
 [4]]
4
[[1]
 [2]
 [3]
 [4]]


In [98]:
a = np.array([[[ 0.67826139,  0.29380381],
                     [ 0.90714982,  0.52835647],
                     [ 0.4215251 ,  0.45017551]],

                   [[ 0.92814219,  0.96677647],
                    [ 0.85304703,  0.52351845],
                    [ 0.19981397,  0.27417313]],

                   [[ 0.60659855,  0.00533165],
                    [ 0.10820313,  0.49978937],
                    [ 0.34144279,  0.94630077]]])
print(a.shape)

print(np.zeros((2,1)))

(3, 3, 2)
[[0.]
 [0.]]
