In [2]:
import numpy as np

# This array is funny because we don't know if it is a row or a column
a = np.random.randn(5)

In [3]:
print(a)

[-1.08551172  0.40275348  1.0872583   1.52085771 -1.48642024]


In [5]:
print(a.shape)

(5,)


In [6]:
print(a.T)

[-1.08551172  0.40275348  1.0872583   1.52085771 -1.48642024]


In [7]:
np.dot(a,a.T)

7.0451300043678735

In [8]:
np.dot(a.T,a)

7.0451300043678735

In [11]:
b = np.random.randn(5)
c = b.T
print(b)
print(c)

[-0.49100731  0.80478511  1.9722609  -1.09501573 -2.72275437]
[-0.49100731  0.80478511  1.9722609  -1.09501573 -2.72275437]


In [13]:
dotbc = np.dot(b,c)
print(dotbc)

13.391031125611551


In [15]:
dotcb = np.dot(c,b)
print(dotcb)

13.391031125611551


In [17]:
d = np.random.randn(5,1)
print(d)

[[-0.03036937]
 [ 0.47586992]
 [-0.20029718]
 [-0.93750131]
 [ 0.00956225]]


In [19]:
e = np.random.randn(1,5)
print(e)

[[ 0.11826484  1.04188355 -1.13576905  1.94195423 -2.2552323 ]]


In [25]:
dotde = np.dot(d,e)
print(dotde)

[[-3.59162898e-03 -3.16413495e-02  3.44925933e-02 -5.89759313e-02
   6.84899898e-02]
 [ 5.62786805e-02  4.95801044e-01 -5.40478332e-01  9.24117612e-01
  -1.07319722e+00]
 [-2.36881142e-02 -2.08686338e-01  2.27491340e-01 -3.88967959e-01
   4.51716674e-01]
 [-1.10873442e-01 -9.76767188e-01  1.06478497e+00 -1.82058463e+00
   2.11428323e+00]
 [ 1.13087812e-03  9.96275233e-03 -1.08605091e-02  1.85694544e-02
  -2.15650981e-02]]


In [26]:
doted = np.dot(e,d)
print(doted)

[[-1.12244897]]
